apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: node-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 8080
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
      tier: backend
  template:
    metadata: 
      labels:
        app: node-app
        tier: backend
    spec: 
      containers:
        - name: second-cont
          image: successtech/k8-app:1
        # - name: ...
        #   image: ...
